# Generated by Django 3.0.1 on 2020-07-07 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('comment', models.TextField(max_length=1000)),
                ('time_published', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fullname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('body', models.TextField()),
                ('auth', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('images', models.ImageField(blank=True, upload_to='')),
                ('views', models.IntegerField(default=0)),
                ('priority', models.CharField(default='Medium', max_length=20)),
                ('comments', models.ManyToManyField(blank=True, null=True, to='articles.Comments')),
            ],
        ),
    ]
