# Generated by Django 3.0.1 on 2020-07-07 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='priority',
        ),
    ]
