# Generated by Django 3.0.1 on 2020-07-07 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_remove_article_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='priority',
            field=models.CharField(default='Medium', max_length=20),
        ),
    ]
